services:
  bot:
    build:
      context: .
    container_name: telegram-bot
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - node_modules/
        - action: rebuild 
          path: requirements.txt
      depends_on:
        - chromadb
    networks:
      - local-network

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    volumes:
      - ./db/index_data:/index_data
    ports:
      - "8000:8000"
    networks:
      - local-network
    environment:
      - CHROMA_SERVER_AUTH_PROVIDER=${CHROMA_SERVER_AUTHN_PROVIDER}
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_SERVER_AUTHN_CREDENTIALS}

networks:
  local-network:
    driver: bridge
    