services:
  bot:
    build:
      context: .
    container_name: telegram-bot
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - node_modules/
        - action: rebuild 
          path: requirements.txt
      depends_on:
        - postgresql-pgvector
    networks:
      - local-network
    ports:
      - 8081:8081
    #   - ollama
    # networks:
    #   - local-network
  # ollama:
  #   image: ollama/ollama:latest
  #   restart: always
  #   container_name: ollama-ai
  #   expose:
  #     - 11434
  #   ports:
  #     - "11434:11434"
  #   deploy:
  #       resources:
  #           limits:
  #             cpus: '2'
  #             memory: 16G
  #   volumes:
  #     - ./dockervolumes/ollama:/root/.ollama
  #     - .:/ollamascript
  #   entrypoint: ["/usr/bin/bash", "/ollamascript/ollamascript.sh"]
  #   networks:
  #     - local-network
  postgresql-pgvector:
      image: pgvector/pgvector:pg16
      container_name: postgresql-pgvector
      env_file:
        - ".env"
      restart: always
      environment:
        - POSTGRES_DB=feedconveyor
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      volumes:
        - ./db:/var/lib/postgresql/data
      networks:
        - local-network
      ports:
        - 8181:5432
        
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    env_file:
      - ".env"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 8080:80
    networks:
      - local-network

networks:
  local-network:
    driver: bridge